#!/bin/bash -l
#SBATCH -J nnodewww_32
#SBATCH -q regular
#SBATCH -o nnodewww_m32.log
#SBATCH -N nodewww
#SBATCH --tasks-per-node=2
#SBATCH --cpus-per-task=68
#SBATCH -C knl,quad,cache
#SBATCH -t 2:00:00

cd $SLURM_SUBMIT_DIR
#module load gamess

./rungms-xt nnodewww_m32.inp  procwww 1
